# Generated by Django 4.1.2 on 2022-12-31 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='Fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='LastName',
        ),
    ]
